### PR TITLE
add season 5 map for 27.11

### PR DESCRIPTION
**Pull request by Ralzify**

### CODE REVIEW

**Comment by Ralzify** [comment]
(make sure to change it to false btw since i forgot to)

**Comment by HybridFNBR** [comment]
stage 1 is active by default if it wasnt i would have added it.

**Comment by Ralzify** [comment]
> Owner

it's stage 4 by default because that one's already enabled.

**Comment by HybridFNBR** [comment]
i mean without stage 4 being active its stage 1 by default, or to simplify it stage one is just the default season OG map

**Pull request closed without merging**
